// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcM-x4hhznHlDcYNVJr9yDlBiUydGB_Eo',
    appId: '1:1058427313682:web:be73749eba35984bb142cb',
    messagingSenderId: '1058427313682',
    projectId: 'search-books-60396',
    authDomain: 'search-books-60396.firebaseapp.com',
    storageBucket: 'search-books-60396.appspot.com',
    measurementId: 'G-WZ5820TK0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfaAFDIHmY-geOtVCzFgQhyQcuXiOic8o',
    appId: '1:1058427313682:android:45f7b29ff1c0936eb142cb',
    messagingSenderId: '1058427313682',
    projectId: 'search-books-60396',
    storageBucket: 'search-books-60396.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiXhfx6pz6_HGdptqzWg1PdEB3o5i8IS0',
    appId: '1:1058427313682:ios:fa2f8cefa68c8ff5b142cb',
    messagingSenderId: '1058427313682',
    projectId: 'search-books-60396',
    storageBucket: 'search-books-60396.appspot.com',
    iosClientId: '1058427313682-4jeau0lt93573mqahnd9sijklu53sk1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSearchBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiXhfx6pz6_HGdptqzWg1PdEB3o5i8IS0',
    appId: '1:1058427313682:ios:fa2f8cefa68c8ff5b142cb',
    messagingSenderId: '1058427313682',
    projectId: 'search-books-60396',
    storageBucket: 'search-books-60396.appspot.com',
    iosClientId: '1058427313682-4jeau0lt93573mqahnd9sijklu53sk1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSearchBook',
  );
}
